site_name: openpaimarketplace
repo_url: https://github.com/microsoft/openpaimarketplace
repo_name: openpaimarketplace
nav:
  - Home: index.md
  - User Manual:
      - Introduction: user/README.md
      - Quick Start: user/quick_start.md
      - Data Management: user/data_management.md
      - Create Template: user/create_template.md
  - Admin Manual:
      - Introduction: admin/README.md
      - Deployment: admin/deployment.md
plugins:
  - search
theme: readthedocs
use_directory_urls: false
