protocolVersion: 2
name: rocm_pytorch_mnist
type: job
version: 1.0
contributor: OpenPAI
description: |
  # ROCm PyTorch MNIST Job Template
  PyTorch MNIST example on AMD GPUs.

parameters:
  epochs: 1
  batchsize: 64
  lr: 0.01

prerequisites:
  - protocolVersion: 2
    name: rocm_torch
    type: dockerimage
    uri : rocm/pytorch:rocm3.9_ubuntu18.04_py3.6_pytorch

taskRoles:
  worker:
    instances: 1
    completion:
      minSucceededInstances: 1
    dockerImage: rocm_torch
    extraContainerOptions:
      shmMB: 4096
    resourcePerInstance:
      cpu: 4
      memoryMB: 8192
      gpu: 1
    commands:
      - git clone https://github.com/pytorch/examples
      - cd examples/mnist
      - pip3 install -r requirements.txt
      - >
        python3 main.py
        --epochs <% $parameters.epochs %>
        --lr <% $parameters.lr %>
        --batch-size <% $parameters.batchsize %>
